=== ErjieIsHeree/WsLMSGIExercises/04.DTD&XSD/13_DTDyXSD/13.3_Ejercicios/13.3_EjercicioValidacionDTD.dtd
<!ELEMENT biblioteca (nombre_biblioteca, seccion*)>

    <!ELEMENT nombre_biblioteca (#PCDATA)>
    <!ELEMENT seccion (libro*)>

        <!ELEMENT libro (titulo,autor,anio?,resumen,editorial)>

            <!ELEMENT titulo (#PCDATA)>
            <!ELEMENT autor (#PCDATA)>
            <!ELEMENT anio (#PCDATA)>
            <!ELEMENT resumen (#PCDATA)>
            <!ELEMENT editorial (codigo?,nombre_editorial,ciudad)>

                <!ELEMENT codigo (#PCDATA)>
                <!ELEMENT nombre_editorial (#PCDATA)>
                <!ELEMENT ciudad (#PCDATA)>

=== ErjieIsHeree/WsLMSGIExercises/04.DTD&XSD/13_DTDyXSD/13.3_Ejercicios/13.3_EjemploXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "13.3_EjercicioValidacionDTD.dtd">
<biblioteca>
  <nombre_biblioteca>Biblioteca nacional</nombre_biblioteca>
  <seccion>
    <libro>
      <titulo>El señor de los anillos</titulo>
      <autor>J.R.R. Tolkien</autor>
      <resumen>Un viaje épico para destruir un anillo mágico.</resumen>
      <editorial>
        <nombre_editorial>Editorial Fantástica</nombre_editorial>
        <ciudad>Barcelona</ciudad>
      </editorial>
    </libro>
    <libro>
      <titulo>Harry Potter y la piedra filosofal</titulo>
      <autor>J.K. Rowling</autor>
      <anio>1997</anio>
      <resumen>Las aventuras de un joven mago en Hogwarts.</resumen>
      <editorial>
        <nombre_editorial>Ediciones Mágicas</nombre_editorial>
        <ciudad>Londres</ciudad>
      </editorial>
    </libro>
  </seccion>
  <seccion>
    <libro>
      <titulo>Cien años de soledad</titulo>
      <autor>Gabriel García Márquez</autor>
      <anio>1967</anio>
      <resumen>La historia de la familia Buendía en Macondo.</resumen>
      <editorial>
        <nombre_editorial>Ediciones Macondo</nombre_editorial>
        <ciudad>Bogotá</ciudad>
      </editorial>
    </libro>
  </seccion>
  <seccion>
    <libro>
      <titulo>1984</titulo>
      <autor>George Orwell</autor>
      <resumen>Un futuro distópico donde el pensamiento está controlado.</resumen>
      <editorial>
		    <codigo>ED45TR</codigo>
        <nombre_editorial>Editorial Distopía</nombre_editorial>
        <ciudad>Londres</ciudad>
      </editorial>
    </libro>
    <libro>
      <titulo>Fundación</titulo>
      <autor>Isaac Asimov</autor>
      <anio>1951</anio>
      <resumen>La historia de la Fundación para prever el futuro galáctico.</resumen>
      <editorial>
        <nombre_editorial>Ediciones Galácticas</nombre_editorial>
        <ciudad>Nueva York</ciudad>
      </editorial>
    </libro>
  </seccion>
  <!-- Puedes agregar más secciones y libros según sea necesario -->
</biblioteca>
